import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getWebsiteSettings } from "@/lib/adminServices";
import LayoutWrapper from "./components/LayoutWrapper";
import { CurrencyProvider } from "@/context/CurrencyContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
 const res = await getWebsiteSettings();

let settings = {};
try {
  settings = JSON.parse(res?.plainsettings ?? "{}");
} catch (err) {
  console.error("Invalid JSON in plainsettings:", err);
  settings = {};
}

console.log(settings);


  return (
    <html lang="en" className="" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
       <CurrencyProvider>
         <LayoutWrapper logo={settings.siteName} siteName={settings.siteName}>
          {children}
        </LayoutWrapper>
       </CurrencyProvider>
      </body>
    </html>
  );
}
